@IAmFurkan.Api_HostAddress = http://localhost:5009

POST {{IAmFurkan.Api_HostAddress}}/auth/register
Content-Type: application/json

{
    "firstName" : "Furkan Bilal",
    "lastName" : "Yigit",
    "email" : "bilalyigit594@gmail.com",
    "password" : "furkan214284"
}

###
